<?php

return [
    0 => 'abyss',
    1 => 'acid',
    2 => 'aqua',
    3 => 'autumn',
    4 => 'black',
    5 => 'bumblebee',
    6 => 'business',
    7 => 'caramellatte',
    8 => 'cmyk',
    9 => 'coffee',
    10 => 'corporate',
    11 => 'cupcake',
    12 => 'cyberpunk',
    13 => 'dark',
    14 => 'dim',
    15 => 'dracula',
    16 => 'emerald',
    17 => 'fantasy',
    18 => 'forest',
    19 => 'garden',
    20 => 'halloween',
    21 => 'lemonade',
    22 => 'light',
    23 => 'lofi',
    24 => 'luxury',
    25 => 'night',
    26 => 'nord',
    27 => 'pastel',
    28 => 'retro',
    29 => 'silk',
    30 => 'sunset',
    31 => 'synthwave',
    32 => 'valentine',
    33 => 'winter',
    34 => 'wireframe',
];
